export const options = [
        { value: 'all', label: 'All Types' },
        { value: 'fire', label: 'Fire' },
        { value: 'water', label: 'Water' },
        { value: 'grass', label: 'Grass' },
        { value: 'electric', label: 'Electric' },
        { value: 'ice', label: 'Ice' },
        { value: 'fighting', label: 'Fighting' },
        { value: 'poison', label: 'Poison' },
        { value: 'ground', label: 'Ground' },
        { value: 'flying', label: 'Flying' },
        { value: 'psychic', label: 'Psychic' },
        { value: 'bug', label: 'Bug' },
        { value: 'rock', label: 'Rock' },
        { value: 'ghost', label: 'Ghost' },
        { value: 'dragon', label: 'Dragon' },
        { value: 'dark', label: 'Dark' },
        { value: 'steel', label: 'Steel' },
        { value: 'fairy', label: 'Fairy' },
]